from typing import Protocol, Any, AsyncIterator, TypeVar

class DriverNotFoundError(Exception):
    pass

class ProviderDriver(Protocol):
    async def validate_connection(self, ctx: Any) -> Any: ...
    async def discover_models(self, ctx: Any) -> list[Any]: ...
    async def execute(self, ctx: Any, request: Any) -> Any: ...
    async def execute_stream(self, ctx: Any, request: Any) -> AsyncIterator[bytes]: ...
    async def fetch_quota(self, ctx: Any) -> list[Any]: ...
    def parse_usage(self, response: Any) -> dict[str, Any]: ...
    def classify_error(self, error_or_response: Any) -> dict[str, Any]: ...
    def capabilities(self) -> dict[str, Any]: ...
